language: generic
sudo: required
services:
  - docker

env:
  global:
    - BUILD_IMAGE="grundrausch3n/ergw-gtp-c-node"
    - BUILDER_IMAGE="grundrausch3n/ergw-gtp-c-node-base"

before_install:
  - docker pull $BUILDER_IMAGE

script:
  - docker build -t $BUILD_IMAGE . 

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $BUILD_IMAGE 
  - echo "Done"

