language: generic
sudo: required
services:
  - docker

env:
  global:
    - BUILD_IMAGE="grundrausch3n/ergw-gtp-c-node"
    - BUILDER_IMAGE="grundrausch3n/ergw-docker-build"

before_install:
  - docker pull $BUILDER_IMAGE

script:
  - mkdir artifacts
  - docker run -v `pwd`:/build $BUILDER_IMAGE
    sh -c "
      cd /build;
      rebar3 as prod release;
    "
  - docker build -t $BUILD_IMAGE . 

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $BUILD_IMAGE 
  - echo "Done"

